export const SentenceInfo = [

    {
        id: "1",
        text1: "Hello",
        text2: "Annyunghaseyo",
        text3: "안녕하세요",
        image: "asset/images/sentence/hello.jpg",
    },
    {
        id: "2",
        text1: "Thank you",
        text2: "gamsahapnida",
        text3: "감사합니다",
        image: "asset/images/sentence/thanku.jpg",
    },
    {
        id: "3",
        text1: "I'm sorry",
        text2: "joesonghapnida",
        text3: "죄송합니다",
        image: "asset/images/sentence/sorry.jpg",
    },
    {
        id: "4",
        text1: "Nice to meet you",
        text2: "bangapseupnida",
        text3: "반갑습니다",
        image: "asset/images/sentence/nice.jpg",
    },
    {
        id: "5",
        text1: "Goodbye",
        text2: "annyeonghigyeseyo",
        text3: "안녕히계세요",
        image: "asset/images/sentence/bye.jpg",
    },
    {
        id: "6",
        text1: "I'm hungry",
        text2: "baegopeupnida ",
        text3: "배고픕니다",
        image: "asset/images/sentence/hungry.jpg",
    },
    {
        id: "7",
        text1: "Hello",
        text2: "Annyunghaseyo",
        text3: "안녕하세요",
        image: "asset/images/sentence/hello.jpg",
    },
    {
        id: "8",
        text1: "Thank you",
        text2: "gamsahapnida",
        text3: "감사합니다",
        image: "asset/images/sentence/thanku.jpg",
    },
    {
        id: "9",
        text1: "I'm sorry",
        text2: "joesonghapnida",
        text3: "죄송합니다",
        image: "asset/images/sentence/sorry.jpg",
    },
    {
        id: "10",
        text1: "Nice to meet you",
        text2: "bangapseupnida",
        text3: "반갑습니다",
        image: "asset/images/sentence/nice.jpg",
    },
    {
        id: "11",
        text1: "Goodbye",
        text2: "annyeonghigyeseyo",
        text3: "안녕히계세요",
        image: "asset/images/sentence/bye.jpg",
    },
    {
        id: "12",
        text1: "I'm hungry",
        text2: "baegopeupnida ",
        text3: "배고픕니다",
        image: "asset/images/sentence/hungry.jpg",
    },
];
