const lyricsList = [
    {
        id: 0,
        title: "NEWJEANS",
        img: "/asset/images/idol/idol1.png",
        path: "/lyrics",
        part1: ["baby 예민하대 나 lately 너 없이는 매일 매일이 yeah 재미없어 어쩌지",
        "Honey, I'm sensitive lately. It's not fun because you're not here every day. What should I do.",
        "baby yeminhadae na lately neo eopsineun maeil maeiri yeah jaemieopseo eojjeoji",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/IQ69bf8uqME?si=Q0XSd3geurkSt_M1&amp;clip=UgkxEMPT3Lk9TFRNUF1C8uylKSoEowXjjEBN&amp;clipt=ENCiAhjU9AI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["내 지난날들은 눈 뜨면 잊는 꿈 Hype boy 너만 원해 Hype boy 내가 전해",
        "My past days are a dream I forget when I open my eyes. Hype boy I only want you Hype boy I tell him",
        "nae jinannaldeureun nun tteumyeon ijneun kkum Hype boy neoman wonhae",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/IQ69bf8uqME?si=-t2hTamC2hN9LyD5&amp;clip=UgkxWSmJI0Zfl-YH_YuzEjSaDgul6bWlU8tV&amp;clipt=ELzgAxjYqgQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["잠에 들려고 잠에 들려 해도 네 생각에 또 새벽 세 시 uh-oh",
        "I tried to sleep, but it's already 3 a.m. thinking about you",
        "jame deullyeogo jame deullyeo haedo ne saenggage tto saebyeok se si uh-oh",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/IQ69bf8uqME?si=dm0zXV2_KgsDSJP9&amp;clip=Ugkx2fc2NaUH7eoDZs1aw9O-tCcOUE9AghSS&amp;clipt=EOzKBRjvgwY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 1,
        title: "BTS",
        img: "/asset/images/idol/idol2.png",
        path: "/lyrics",
        part1: ["내 피 땀 눈물 내 마지막 춤을 내 피 땀 눈물 내 차가운 숨을 다 가져가 가",
        "Take my blood, sweat, tears, and the last dance. Take my blood, sweat, tears, my cold breath.",
        "nae pi ttam nunmul nae majimak chumeul nae pi ttam nunmul nae chagaun sumeul da gajyeoga ga",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/32xlppvyWC8?si=a7R5FL3ZTlt47ii8&amp;clip=Ugkx7YRgC0vfhAWzB_BA8A1ha7PXTeZ4Sn6s&amp;clipt=EKCQBRjEswY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["아파도 돼 날 묶어줘 내가 도망칠 수 없게 꽉 쥐고 날 흔들어줘 내가 정신 못 차리게",
        "It's okay to be sick. Tie me up so I can't run away. Hold me tight and shake me so I can't get myself together.",
        "apado dwae nal mukkeojwo naega domangchil su eopsge kkwak jwigo nal heundeureojwo naega jeongsin mot charige",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/32xlppvyWC8?si=UBrA0TYJCenBjJnk&amp;clip=UgkxQMjuC71goNtjZuV92_2QY_zJ-_YqOZk3&amp;clipt=EOjWBxiTpAg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["어차피 거부할 수조차 없어 더는 도망갈 수조차 없어 니가 너무 달콤해 너무 달콤해 너무 달콤해서",
        "I can't even refuse it. I can't even run away anymore. because you're so sweet, because you're so sweet, because you're so sweet.",
        "eochapi geobuhal sujocha eopseo deoneun domanggal sujocha eopseo niga neomu dalkomhae neomu dalkomhae neomu dalkomhaeseo ",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/32xlppvyWC8?si=fgE_dNyZknKzWK1x&amp;clip=UgkxKTe762a585XtDOsyW5XF5Q1ug3CjsdZu&amp;clipt=EPyGDBjH2gw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 2,
        title: "NCT DREAM",
        img: "/asset/images/idol/idol3.png",
        path: "/lyrics",
        part1: ["어렵게 맘 정한 거라 네게 말할 거지만 사실 오늘 아침에 그냥 나 생각한 거야",
        "I'm going to tell you because it's hard to make up my mind but this morning, I thought of myself",
        "eoryeopge mam jeonghan geora nege malhal geojiman sasil oneul achime geunyang na saenggakhan geoya",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ipZaXDC23Bw?si=cYXoUS7KMIV_xzFx&amp;clip=Ugkx8AagmbqKLz-FatKus_bMcIEhTZWd_T8w&amp;clipt=EPykAhiE5QI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["머리 위로 비친 내 하늘 바라다보며 널 향한 마음을 이제는 굳혔지만",
        "I look at my sky reflected above my head and my heart for you is now solidified",
        "meori wiro bichin nae haneul baradabomyeo neol hyanghan maeumeul ijeneun guthyeossjiman",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ipZaXDC23Bw?si=Kj_cwD12tG2NItP9&amp;clip=UgkxweQOxzFpKHFtNvOG8Z8b9hjNFVGKJFY6&amp;clipt=EOjfBBi4oQU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["단지 널 사랑해 이렇게 말했지 이제껏 준비했던 많은 말을 뒤로한 채",
        "I just said that I love you, leaving behind a lot of things I've prepared",
        "danji neol saranghae ireohge malhaessji ijekkeot junbihaessdeon manheun mareul dwirohan chae",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ipZaXDC23Bw?si=aTe4KZkF_6tD0dXr&amp;clip=UgkxAEW3xLHOnoLPizvZNOjMEKe9Wd8h6vGY&amp;clipt=EJjmBRiIrgY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 3,
        title: "BLACKPINK",
        img: "/asset/images/idol/idol4.png",
        path: "/lyrics",
        part1: ["얼굴이 뜨겁고 가슴은 계속 뛰어 내 몸이 맘대로 안 돼 어지러워",
        "My face is hot, my chest keeps jumping, my body can't control I'm dizzy",
        "eolguri tteugeopgo gaseumeun gyesok ttwieo nae momi mamdaero an dwae eojireowo ",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ucrKgXlKfe4?si=5suNQ6E2F6q2vSC6&amp;clip=UgkxldPAaunE0vLUJTN0iznTt_VoT5pwybQw&amp;clipt=EPynARis4wE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["Baby, 날 터질 것처럼 안아줘 그만 생각해 뭐가 그리 어려워",
        "Baby, hug me like I'm going to explode Stop thinking about it What's so difficult",
        "baby, nal teojil geoscheoreom anajwo geuman saenggakhae mwoga geuri eoryeowo",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ucrKgXlKfe4?si=cIBvfGUVdW5dA4Gr&amp;clip=Ugkxujqlz3GArZWmYwMBRkuaFO8CaNwT_ujc&amp;clipt=EMjcAxjfnwQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["마지막처럼 마-마-마지막처럼 마지막 밤인 것처럼 love 마지막처럼 마-마-마지막처럼 내일 따윈 없는 것처럼",
        "Like the last, like the last, like the last night, like the last, like the last, like the last, like the last, like the last, like there's no tomorrow",
        "majimakcheoreom ma-ma-majimakcheoreom majimak bamin geoscheoreom love majimakcheoreom ma-ma-majimakcheoreom naeil ttawin eopsneun geoscheoreom ",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/ucrKgXlKfe4?si=1R5MaRzSDKANjtkP&amp;clip=UgkxJOAXHXNySQfZocoaRrR7xjSMLp2U234V&amp;clipt=EJDbBBjw0QU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 4,
        title: "AESPA",
        img: "/asset/images/idol/idol5.png",
        path: "/lyrics",
        part1: ["절대적 룰을 지켜 내 손을 놓지 말아 결속은 나의 무기",
        "I obey the absolute rules. Don't let go of my hand. Bonding is my weapon",
        "jeoldaejeok rureul jikyeo nae soneul nohji mara gyeolsogeun naui mugi",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/9qyt9baCsQc?si=fV9KMlWicMVHKdon&amp;clip=UgkxhrTY3FtALh_l9OfYs8xoinr8iYHcWOBw&amp;clipt=EKyxARiQ5AE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["감당할 수 없는 절망도 내 믿음을 깨지 못해",
        "I can't handle the hopelessness, I can't break my faith",
        "gamdanghal su eopsneun jeolmangdo nae mideumeul kkaeji moshae",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/9qyt9baCsQc?si=vLEm_ksuWXvQIh3C&amp;clip=Ugkxor-UvzlFXixNCxV7wdszZ7zoGiXFYagq&amp;clipt=EPDOBhj3jgc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["중심을 잃고 목소리도 잃고 비난받고 사람들과 멀어지는 착각 속에",
        "In the illusion of losing balance, losing voice, being criticized, and moving away from people",
        "jungsimeul ilhgo moksorido ilhgo binanbatgo saramdeulgwa meoreojineun chakgak soge",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/9qyt9baCsQc?si=gi_xKsULmcX7uoJ2&amp;clip=UgkxjCdm1tUY6fzAqIskxKYXNhvne5GPBGYm&amp;clipt=EKzLCRio9gk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 5,
        title: "IVE",
        img: "/asset/images/idol/idol6.png",
        path: "/lyrics",
        part1: ["참을 수 없는 이끌림과 호기심 묘한 너와 나 두고 보면 알겠지",
        "Unbearable attraction and curiosity. You and I will see",
        "chameul su eopsneun ikkeullimgwa hogisim myohan neowa na dugo bomyeon algessji ",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/VkCRg_p9-_A?si=_tLdpTAGp52q_Hcj&amp;clip=Ugkx9KujPGxueZITZncobuquJnCIN60eEhKn&amp;clipt=EKi9Axjo-wM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["Woo 눈동자 아래로 Woo 감추고 있는 거",
        "Woo hiding under his eyes",
        "Woo nundongja araero Woo gamchugo issneun geo",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/VkCRg_p9-_A?si=_ZqZduRY9dNpJ0Hx&amp;clip=UgkxyKwcFtimMAoYpebogTpqE7s2Dh3RnH2I&amp;clipt=EOj7Axj_vgQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["아름다운 까만 눈빛 더 빠져 깊이 (넌 내게로 난 네게로) 숨 참고 love dive",
        "My beautiful black eyes fall deeper (You come to me, I come to you) Hold your breath and love give",
        "areumdaun kkaman nunbit deo ppajyeo gipi (neon naegero nan negero) sum chamgo love dive",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/VkCRg_p9-_A?si=7cGwn3Ia7-itFKpy&amp;clip=UgkxfTtDaVipkUAjFQRStyakXX_wfGi7zXvr&amp;clipt=EMCvBRjI1gU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 6,
        title: "NCT 127",
        img: "/asset/images/idol/idol7.png",
        path: "/lyrics",
        part1: ["아무 생각 말고 너의 이야기대로 걸어 어두운 어제가 오늘을 삼켜 버리기 전에",
        "Don't think about anything and walk according to your story before the dark yesterday swallows up today",
        "amu saenggak malgo neoui iyagidaero georeo eoduun eojega oneureul samkyeo beorigi jeone",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/rrUxPFklKS8?si=UNpqN7M0MK_KVylD&amp;clip=Ugkx-IGVwMlz7BSQjBADpD-IPrsb2uxNfzHM&amp;clipt=ELjZAxjrmwQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["난 앞으로 찔러 좌우 new thangs new thangs new thangs 우리가 어딜 가든 축제 들어 축배",
        "I poke forward, left and right, new thangs, new thangs, wherever we go, go to the festival, toast",
        "nan apeuro jjilleo jwau new thangt new thangt new thangt uriga eodil gadeun chukje deureo chukbae",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/rrUxPFklKS8?si=cRZCUs03Ld5o1o3O&amp;clip=Ugkx_ID-EvKE88QE3Feq9nM0CEa0o0Es4T-J&amp;clipt=EOCcBRio6QU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["눈앞에 펼쳐질 새로운 세상들 손안에 잡힐 듯 내 안으로 들어와",
        "The new worlds that will unfold in front of you come into me like you're going to be in your hands",
        "nunape pyeolchyeojil saeroun sesangdeul sonane japhil deut nae aneuro deureowa",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/rrUxPFklKS8?si=WnsSEU6_KnowoOei&amp;clip=UgkxtaLypBM7t_etUBKdCXRwr2SGHKW9Ehk5&amp;clipt=EIiGCxjDvQs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
    {
        id: 7,
        title: "SEVENTEEN",
        img: "/asset/images/idol/idol8.png",
        path: "/lyrics",
        part1: ["무뚝뚝한 내가 이젠 평소 에도 널 걱정해 길을 걸을 때 Baby",
        "I'm blunt now I worry about you when I'm walking down the street baby",
        "muttukttukhan naega ijen pyeongso edo neol geokjeonghae gireul georeul ttae baby ",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/U8vmUH5CqHk?si=onG2c5kRmwPFdTn2&amp;clip=UgkxDTSoD_PPvCCiIT6sieLPvaMP8AVB4XgL&amp;clipt=ELCAAxigrwM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part2: ["잠깐 소녀야 절대 넌 다른 사람에게 녹지마 내가 질투 나잖아",
        "jamkkan sonyeoya jeoldae neon dareun saramege nokjima naega jiltu najanha",
        "nae pi ttam nunmul nae majimak chumeul",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/U8vmUH5CqHk?si=d5hY5LCiUi-sfkpl&amp;clip=UgkxBloM5FD8oRuf0oiCnGJAAg1JxDSY2edT&amp;clipt=EPC-AxikgQQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
        part3: ["너라는 꽃이 피었습니다 너라는 꽃을 바라보니까 들었나 놨다 하지 맙시다 애가 타니까",
        "A flower called 'You' has bloomed. Let's not hold it up or down. It's burning",
        "neoraneun kkocci pieossseupnida neoraneun kkocceul barabonikka deureossna nwassda haji mapsida aega tanikka",
        <iframe width="560" height="315" src="https://www.youtube.com/embed/U8vmUH5CqHk?si=iwTT7cvexdhtpITY&amp;clip=UgkxPK8of7gFr-BrWg_ksfP8uSFbkZxQiT3j&amp;clipt=EKjQBRj3kQY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>],
    },
];

export default lyricsList;