const lyricsList = [
    {
        id: 0,
        title: "NEWJEANS",
        img: "asset/images/idol/idol1.png",
        contents: "내 지난날들은 눈 뜨면 잊는 꿈 Hype boy 너만 원해",
        english: "My past days are a dream I forget when I open my eyes Hype boy I only want you",
        pronun: "nae jinannaldeureun nun tteumyeon ijneun kkum Hype boy neoman wonhae",
        path: "/lyrics",
    },
    {
        id: 1,
        title: "BTS",
        img: "asset/images/idol/idol2.png",
        contents: "내 피 땀 눈물 내 마지막 춤을",
        english: "My blood, sweat, tears, my last dance",
        pronun: "nae pi ttam nunmul nae majimak chumeul",
    },
    {
        id: 2,
        title: "NCT DREAM",
        img: "asset/images/idol/idol3.png",
        english: "I just said I love you",
        pronun: "danji neol saranghae ireohge malhaessji",
        contents: "단지 널 사랑해 이렇게 말했지",
        path: "/lyrics",
    },
    {
        id: 3,
        title: "BLACKPINK",
        img: "asset/images/idol/idol4.png",
        english: "Baby, hug me like I'm going to explode Stop thinking about it What's so difficult",
        pronun: "baby, nal teojil geoscheoreom anajwo geuman saenggakhae mwoga geuri eoryeowo ",
        contents: "Baby, 날 터질 것처럼 안아줘 그만 생각해 뭐가 그리 어려워",
        path: "/lyrics",
    },
    {
        id: 4,
        title: "AESPA",
        img: "asset/images/idol/idol5.png",
        english: "I can't handle the hopelessness, I can't break my faith",
        pronun: "gamdanghal su eopsneun jeolmangdo nae mideumeul kkaeji moshae",
        contents: "감당할 수 없는 절망도 내 믿음을 깨지 못해",
        path: "/lyrics",
    },
    {
        id: 5,
        title: "IVE",
        img: "asset/images/idol/idol6.png",
        english: "My beautiful black eyes fall deeper, hold your breath, love give",
        pronun: "areumdaun kkaman nunbit deo ppajyeo gipi sum chamgo love dive ",
        contents: "아름다운 까만 눈빛 더 빠져 깊이 숨 참고 love dive",
        path: "/lyrics",
    },
    {
        id: 6,
        title: "NCT 127",
        img: "asset/images/idol/idol7.png",
        english: "I poke forward, left and right, new thang Wherever we go, festival",
        pronun: "nan apeuro jjilleo jwau, new thang uriga eodil gadeun chukje",
        contents: "난 앞으로 찔러 좌우, new thang 우리가 어딜 가든 축제",
        path: "/lyrics",
    },
    {
        id: 7,
        title: "SEVENTEEN",
        img: "asset/images/idol/idol8.png",
        english: "jamkkan sonyeoya jeoldae neon dareun saramege nokjima naega jiltu najanha ",
        pronun: "nae pi ttam nunmul nae majimak chumeul",
        contents: "잠깐 소녀야 절대 넌 다른 사람에게 녹지마 내가 질투 나잖아",
        path: "/lyrics",
    },
];

export default lyricsList;